version: '3.3'
services:
  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
#    image: elasticsearch:6.8.1
    image: elasticsearch:6.6.0
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "TZ=Asia/Shanghai"
    ulimits:
      memlock:
        soft: -1
        hard: -1